pipeline:
  name: devopsdemo-cicd
  identifier: devopsdemocicd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: adityagithubconn
        build: <+input>
  stages:
    - stage:
        name: Build-FastAPI
        identifier: BuildFastAPI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Test-FastAPI
                  identifier: TestFastAPI
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      pip install -r requirements.txt
                      pytest -v
              - step:
                  type: BuildAndPushACR
                  name: Build-Push-Image
                  identifier: BuildPushImage
                  spec:
                    connectorRef: Azure_connector_aditya
                    repository: devopsdemoacr.azurecr.io/devops-demo
                    subscriptionId: 6f1bb50b-55ac-48dc-ab4c-e68a7dc49927
                    tags:
                      - <+pipeline.variables.IMAGE_TAG>
                    dockerfile: app/Dockerfile
                    context: app
    - stage:
        name: Deploy to Dev
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: fastapiservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devaksinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: approval
        identifier: approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approve Prod Deployment
                  identifier: Approve_Prod_Deployment
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy to Prod
        identifier: Deploy_to_Prod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: Deploy_to_Dev
          environment:
            environmentRef: prod
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prodharnessinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: IMAGE_TAG
      type: String
      description: ""
      required: false
      value: v1
